// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGPJtSgngXhz8TLehshGddxlbqBtI6RXs',
    appId: '1:576032151578:web:4f00e005a29d9c29e1d9a3',
    messagingSenderId: '576032151578',
    projectId: 'tracking-a4e2b',
    authDomain: 'tracking-a4e2b.firebaseapp.com',
    storageBucket: 'tracking-a4e2b.firebasestorage.app',
    measurementId: 'G-7RXHZ0L30X',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfd3T0CUPi4OQLuv7bje-sHqw7Znz_exM',
    appId: '1:576032151578:ios:362fca022b50a59be1d9a3',
    messagingSenderId: '576032151578',
    projectId: 'tracking-a4e2b',
    storageBucket: 'tracking-a4e2b.firebasestorage.app',
    iosBundleId: 'com.example.equipmentTrackingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGPJtSgngXhz8TLehshGddxlbqBtI6RXs',
    appId: '1:576032151578:web:cf890878f3c8cc01e1d9a3',
    messagingSenderId: '576032151578',
    projectId: 'tracking-a4e2b',
    authDomain: 'tracking-a4e2b.firebaseapp.com',
    storageBucket: 'tracking-a4e2b.firebasestorage.app',
    measurementId: 'G-KD7P8XK1QR',
  );
}
